baseURL = "https://example.com"
title = "BlockAnalytics"
author = "Jérémy RONK"
#Site description
description = "Uncovering Blockchain Insights, Empowering Smarter Moves"
DefaultContentLanguage = "en"
enableMultilingual = true
enableInlineShortcodes = true
defaultContentLanguageInSubdir = true


theme = "Blonde"
enableRobotsTXT = true
tableOfContents = true


# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

# Disqus Comment System
#disqusShortname = ""

[params]
tableOfContents = true


# Base color of the website.
# https://tailwindcss.com/docs/background-color
base_color = "bg-gray-800"



# The number of articles to be displayed on a single page.
paginator_pages = 5
enableEmoji= true
# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "true"

# Number of tags to be displayed.
tagsLimit = 20

# Dark mode by default : dark
# Light mode by default : light
darkmode = "dark"

[languages] 
   [languages.en]
    baseURL = "https://example.com/en"
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Block Insight'
    weight = 1

    
  [languages.fr]
    baseURL = "https://example.com/fr"
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = 'Block Insight'
    weight = 2

    
  
  [params.post]
    # Show thumbnails
    thumbnail = true

    # Disable the "NO IMAGE" image.
    noimage = false

    # See the Tailwind CSS documentation to set it up.
    # Recommended settings are h-32 to h-48.
    # https://tailwindcss.com/docs/height
    thumbnail_height = "lg:h-44"

    # https://tailwindcss.com/docs/width
    thumbnail_width = "lg:w-auto"

    # Number of characters in description
    description = "130"

  [params.widgets]
    # Display widgets
    display = true

    # Order of widgets to display
    widgets = ["search", "archive", "category", "tags", "recent"]

# If you're using Yandex.Metrica, you can enable this feature.
#[params.analytics.yandexmetrica]
#    enabled = true
#    tagNumber = ''


    

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true